#!/bin/sh

set -e

cd ${AUTOPKGTEST_TMP}
for p in $(py3versions -s); do
    $p -m pytest $(python3 -c "import pkg_resources; print(pkg_resources.get_distribution('mock').location)")/mock/tests/test*.py -o cache_dir=${AUTOPKGTEST_TMP}
done
